Eval
RMPR/atbswp pull request #54
Opened 2021-04-29 13:51 UTC by WesleyMPG

It's not finished, but works. 

The first problem was to stop a regular playback without wait for it finish. I couldn't think anything to do that the way things were with the capture file. So the idea is capture file should be just a text file in which each line is the python command (basically the way it is now, but text file instead python file).
Python has a funtion called eval() that executes the content of a string as python commands. This way commands can be executed in a loop that can be interrupted by a flag.

The second problem was the while starting threads. Atbswp frozes because this while blocks the program execution. To solve that just delegated the while to a thread.

It's important to say that it is not ready to merge yet. Changes are in a tempory state and the code is not as i described yet. The ideia is that and it's working more or less that way, but need to be polished. Most the capture file handling.

2021-04-29 15:33 UTC, RMPR commented
> It&#39;s not finished, but works.
>
> The first problem was to stop a regular playback without wait for it
> finish. I couldn&#39;t think anything to do that the way things were
> with the capture file. So the idea is capture file should be just a text
> file in which each line is the python command (basically the way it is
> now, but text file instead python file).
> Python has a funtion called eval() that executes the content of a string
> as python commands. This way commands can be executed in a loop that can
> be interrupted by a flag.
>
> The second problem was the while starting threads. Atbswp frozes because
> this while blocks the program execution. To solve that just delegated
> the while to a thread.


Thanks for the patch, it seems to work as advertised. Tbh, 
I had a fix more or less ready for the infinite playback thing, on the 
`develop` branch.
You can `git checkout develop` and have a quick look if it works for 
you, especially this commit[0] and this one[1]. Keep in mind that, even
though it might work, you can still help me spot bugs that might get
overlooked otherwise. Here's[2] the corresponding announcement in the
community and a small write-up about how and why things were implemented
that way, if you are interested. I think we can get to a satisfying
solution working together.

0:
https://github.com/RMPR/atbswp/commit/345de950bed2c8f98a1586fff1f9beed3f76162b


1:
https://github.com/RMPR/atbswp/commit/1861540857302e31042ec36df213728188ca4dc8


2: https://t.me/atbswp/41

2021-04-29 15:35 UTC, RMPR requested changes

2021-04-29 15:35 UTC, RMPR commented on atbswp/temp.py
> +
It seems like you accidentally pushed the file your are using for tests.

2021-04-29 15:35 UTC, RMPR commented on atbswp/control.py
> +            os.execl(path, *sys.argv)
This might lead to a crash (see my comment on the PR)

2021-04-29 15:39 UTC, RMPR requested changes

2021-04-29 15:39 UTC, RMPR commented on atbswp/temp.py
> +
It seems like you accidentally pushed the file your are using for tests.

2021-04-29 19:39 UTC, WesleyMPG commented on atbswp/temp.py
> +
Sorry for that. I had accidentaly reseted my .gitiginore haha

2021-04-29 20:03 UTC, WesleyMPG commented on atbswp/control.py
> +            os.execl(path, *sys.argv)
I realized now that i made the changes based on master. And seeing your fix I was like: we did the same thing haha. If you asked me before i would swear that the exec on play function was also some os.exec and the playback was a separated program.

2021-04-30 05:53 UTC, RMPR commented
> I realized now that i made the changes based on master. And seeing your
> fix I was like: we did the same thing haha. 

Yeah :) the same idea prevails. By the way, it seems like my changes
introduced a bug with the repeat count (I will upload a GIF). I think it's 
a synchronization bug with threads. I plan to investigate when I
have time, but if you're still interested in working on that feature, 
feel free to spot the error in my code.


> If you asked me before i
> would swear that the exec on play function was also some os.exec and the
> playback was a separated program.

That's why I removed it all together, it didn't make much sense to me at
that point.

2021-04-30 05:57 UTC, RMPR commented
![atbswp repeat count issue](https://user-images.githubusercontent.com/23162145/116654546-45b07680-a981-11eb-88fd-b8772cfce775.gif)

Sorry for the quality.

2021-04-30 09:26 UTC, WesleyMPG commented
First of all, I pressed the Review request by mistake haha. 
And I can give a look for this repeat counter bug.

2021-05-01 07:30 UTC, RMPR commented
Closing this PR since it's not useful anymore.

2021-05-01 07:30 UTC, closed without merging